
branches:
  only:
    - restructure

language: objective-c

env:
   - TEST_DIR=HelloMap.Objective-C
   - TEST_DIR=AdvancedMap.Objective-C
   - TEST_DIR=CartoMap.Objective-C

script: cd $TEST_DIR && xcodebuild -workspace $TEST_DIR.xcodeproj -scheme $TEST_DIR -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO