
branches:
  only:
    - master

language: objective-c

osx_image: xcode7.3

env:
   - DIR=HelloMap.Objective-C
   - DIR=AdvancedMap.Objective-C
   - DIR=CartoMap.Objective-C

script: cd $DIR && pod update && xcodebuild -workspace $DIR.xcworkspace -scheme $DIR -sdk iphonesimulator -arch "i386" ONLY_ACTIVE_ARCH=NO VALID_ARCHS="i386 x86_64" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean install

