platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'HelloMap.Swift' do
  pod 'CartoMobileSDK', '4.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
