platform :ios, '9.0'

target 'AdvancedMap.Objective-C' do
  pod 'CartoMobileSDK', '= 4.1.0'
  pod 'Toast', '~> 3.0'

  target 'AdvancedMap.Objective-C.UITests' do
  	inherit! :search_paths
  	pod 'CartoMobileSDK', '= 4.1.0'
  	pod 'Toast', '~> 3.0'
  end

end